schemaVersion: 2.2.0
metadata:
  name: delivery-service-dev
  version: 1.0.0
projects:
  - name: delivery-service
    git:
      remotes:
        origin: 'https://github.com/maximilianoPizarro/delivery-service.git'
      checkoutFrom:
        revision: main
components:
  - id: redhat/java11/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - id: redhat/dependency-analytics/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: health-checks-endpoint
        port: 8080
    memoryLimit: 1024Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/jboss/.m2
      - name: config
        containerPath: /home/jboss/.config
      - name: npm
        containerPath: /home/jboss/.npm
    alias: maven
    image: 'quay.io/maximilianopizarro/codeready-jhipster@sha256:cff26c55fda6d79b75570f012161a0aad771b0052b63db97d9aab26d806fa6ad'
    env:
      - value: '-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/jboss'
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
commands:
  - name: 1. Build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/delivery-service'
        type: exec
        command: npm install
        component: maven
  - name: 2. Build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/delivery-service'
        type: exec
        command: mvn clean install -DskipTest
        component: maven
  - name: Debug remote java application
    actions:
      - referenceContent: |
          {
           "version": "0.2.0",
           "configurations": [
             {
               "type": "java",
               "name": "Debug (Attach) - Remote",
               "request": "attach",
               "hostName": "localhost",
               "port": 8080
             }]
           }
        type: vscode-launch
